### ISSUE TITLE
update `package.json` for npm/hardhat usage

### ISSUE THREAD

**Issue by cruzdanilo** [fei-protocol/ERC4626#20]

**Comment by Joeysantoro** [comment]
one of the devs will do this 🤝

**Comment by thomas-waite** [comment]
@cruzdanilo  I'll look into this today and push a fix/update

**Comment by thomas-waite** [comment]
@cruzdanilo  Have a PR here: https://github.com/fei-protocol/ERC4626/pull/21 . Will let you know once merged and I've published the package along with it's name

**Comment by thomas-waite** [comment]
@cruzdanilo This is published now at: https://www.npmjs.com/package/@fei-protocol/erc4626 

Have installed myself and looks good. I'll close this issue now - feel free to reopen if any issues!
